const POKEMON_DB = {
  フシギバナ: {
    name: "フシギバナ",
    type: "くさ",
    no: 3,
    base: { hp: 80, atk: 82, def: 83, spd: 80 },
    sprite_front:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png",
    sprite_back:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/3.png",
    moves: ["はなびらのまい", "ヘドロばくだん", "じしん", "エナジーボール"],
  },
  リザードン: {
    name: "リザードン",
    type: "ほのお",
    no: 6,
    base: { hp: 78, atk: 84, def: 78, spd: 100 },
    sprite_front:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png",
    sprite_back:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/6.png",
    moves: ["かえんほうしゃ", "エアスラッシュ", "りゅうのはどう", "きりさく"],
  },
  カメックス: {
    name: "カメックス",
    type: "みず",
    no: 9,
    base: { hp: 79, atk: 83, def: 100, spd: 78 },
    sprite_front:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png",
    sprite_back:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/9.png",
    moves: ["ハイドロポンプ", "れいとうビーム", "かみつく", "アクアテール"],
  },
  ピカチュウ: {
    name: "ピカチュウ",
    type: "でんき",
    no: 25,
    base: { hp: 35, atk: 55, def: 40, spd: 90 },
    sprite_front:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png",
    sprite_back:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/25.png",
    moves: ["10まんボルト", "でんこうせっか", "アイアンテール", "なきごえ"],
  },
  レックウザ: {
    name: "レックウザ",
    type: "ドラゴン",
    no: 384,
    base: { hp: 105, atk: 150, def: 90, spd: 95 },
    sprite_front:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/384.png",
    sprite_back:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/384.png",
    moves: ["ドラゴンクロー", "たつまき", "りゅうのはどう", "かみくだく"],
  },
};

// 命中率・ひるみ等も反映済
const movesData = {
  はなびらのまい: {
    name: "はなびらのまい",
    type: "くさ",
    power: 120,
    maxPP: 10,
    category: "special",
    accuracy: 100,
    desc: "2-3ターン攻撃後こんらん",
    en: "Petal Dance",
  },
  ヘドロばくだん: {
    name: "ヘドロばくだん",
    type: "どく",
    power: 90,
    maxPP: 10,
    category: "special",
    accuracy: 100,
    desc: "30%でどく",
    en: "Sludge Bomb",
  },
  じしん: {
    name: "じしん",
    type: "じめん",
    power: 100,
    maxPP: 10,
    category: "physical",
    accuracy: 100,
    desc: "相手全体攻撃",
    en: "Earthquake",
  },
  エナジーボール: {
    name: "エナジーボール",
    type: "くさ",
    power: 90,
    maxPP: 10,
    category: "special",
    accuracy: 100,
    desc: "10%で特防↓",
    en: "Energy Ball",
  },
  かえんほうしゃ: {
    name: "かえんほうしゃ",
    type: "ほのお",
    power: 90,
    maxPP: 15,
    category: "special",
    accuracy: 100,
    desc: "10%でやけど",
    en: "Flamethrower",
  },
  エアスラッシュ: {
    name: "エアスラッシュ",
    type: "ひこう",
    power: 75,
    maxPP: 15,
    category: "special",
    accuracy: 95,
    desc: "30%でひるみ",
    en: "Air Slash",
  },
  りゅうのはどう: {
    name: "りゅうのはどう",
    type: "ドラゴン",
    power: 85,
    maxPP: 10,
    category: "special",
    accuracy: 100,
    desc: "通常攻撃",
    en: "Dragon Pulse",
  },
  きりさく: {
    name: "きりさく",
    type: "ノーマル",
    power: 70,
    maxPP: 20,
    category: "physical",
    accuracy: 100,
    desc: "急所に当たりやすい",
    en: "Slash",
  },
  ハイドロポンプ: {
    name: "ハイドロポンプ",
    type: "みず",
    power: 110,
    maxPP: 5,
    category: "special",
    accuracy: 80,
    desc: "命中やや低め",
    en: "Hydro Pump",
  },
  れいとうビーム: {
    name: "れいとうビーム",
    type: "こおり",
    power: 90,
    maxPP: 10,
    category: "special",
    accuracy: 100,
    desc: "10%でこおり",
    en: "Ice Beam",
  },
  かみつく: {
    name: "かみつく",
    type: "あく",
    power: 60,
    maxPP: 25,
    category: "physical",
    accuracy: 100,
    desc: "30%でひるみ",
    en: "Bite",
  },
  アクアテール: {
    name: "アクアテール",
    type: "みず",
    power: 90,
    maxPP: 10,
    category: "physical",
    accuracy: 90,
    desc: "通常攻撃",
    en: "Aqua Tail",
  },
  "10まんボルト": {
    name: "10まんボルト",
    type: "でんき",
    power: 90,
    maxPP: 15,
    category: "special",
    accuracy: 100,
    desc: "10%でまひ",
    en: "Thunderbolt",
  },
  でんこうせっか: {
    name: "でんこうせっか",
    type: "ノーマル",
    power: 40,
    maxPP: 30,
    category: "physical",
    accuracy: 100,
    desc: "先制攻撃",
    en: "Quick Attack",
  },
  アイアンテール: {
    name: "アイアンテール",
    type: "はがね",
    power: 100,
    maxPP: 15,
    category: "physical",
    accuracy: 75,
    desc: "30%で防御↓",
    en: "Iron Tail",
  },
  なきごえ: {
    name: "なきごえ",
    type: "ノーマル",
    power: 0,
    maxPP: 40,
    category: "status",
    accuracy: 100,
    desc: "相手のこうげき↓",
    en: "Growl",
  },
  ドラゴンクロー: {
    name: "ドラゴンクロー",
    type: "ドラゴン",
    power: 80,
    maxPP: 15,
    category: "physical",
    accuracy: 100,
    desc: "通常攻撃",
    en: "Dragon Claw",
  },
  たつまき: {
    name: "たつまき",
    type: "ドラゴン",
    power: 40,
    maxPP: 20,
    category: "special",
    accuracy: 100,
    desc: "20%でひるみ",
    en: "Twister",
  },
  かみくだく: {
    name: "かみくだく",
    type: "あく",
    power: 80,
    maxPP: 15,
    category: "physical",
    accuracy: 100,
    desc: "20%で防御↓",
    en: "Crunch",
  },
};
